server:
  port: 8000

spring:
  application:
    name: gulimall-member
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.161:3306/gulimall_ums?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 192.168.31.161
    port: 6379


mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.study.gulimall.member.entity
  global-config:
    db-config:
      id-type: auto