server:
  port: 10000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.161:3306/gulimall_pms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.31.161
    port: 6379
  session:
    store-type: redis



mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.study.gulimall.product.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.study.gulimall.product: debug


