server:
  port: 12000
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.31.161
    port: 6379
  session:
    store-type: redis
