server:
  port: 20000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.31.161
    port: 6379
  session:
    store-type: redis



logging:
  level:
    com.study.gulimall.product: debug


