server:
  port: 11000


spring:
  application:
    name: gulimall-ware
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.161:3306/gulimall_wms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.31.161
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: mszl_order_group
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.study.gulimall.ware.entity
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.study: debug